### ISSUE TITLE
using random values with `--target wasm32-unknown-unknown`

### ISSUE THREAD

**Issue by DougAnderson444** [DouglasDwyer/wasm_runtime_layer#26]
Hello Douglas, I've been really loving this runtime layer framework you've built!

I'm trying to build wasm components that depend on `rand` though, which works fine for `wasip1`, but I'm running into a wall with the `unknown` target.

The classic way to do this is `getrandom` with the `js` feature, which but when I run:

```bash
cargo component build --target wasm32-unknown-unknown
```

it returns the `module requires an import interface named `__wbindgen_placeholder__`` error.

Of course, it cannot be stubbed because I actually want to use the imported random feature.

Any ideas on how to work around this? Happy to help build whatever is needed, but thought I would ask first!

**Comment by DouglasDwyer** [comment]
Hey there, thanks for reaching out.

`getrandom` with the `js` feature needs a Javascript environment and WASM bindgen in order to function. Raw WASM modules emitted with `cargo build` won't work. The reason `getrandom` requires this feature on WASM is that `rand` needs a way to read raw bytes from the operating system to seed random number generators. As such, I think your options are either to:

- Fork `rand` and replace the `js` feature with something that just returns the same constant seed every time. This will make the RNG in the program deterministic, but maybe that's fine.
- Fork `rand` and add a call to a custom WASM function that your component imports and the host supplies. On the host, you can program this function to return truly random bytes.

Let me know if that helps. I know these suggestions are a bit involved. However, by definition `wasm32-unknown-unknown` is WASM without any notion of a host. So any downstream crates (which aren't familiar with where the WASM will be running) cannot innately support reading random bytes by calling an OS function, which is what I believe `rand` does.

**Comment by DougAnderson444** [comment]
Those are interesting ideas!

What about targeting `wasm32-wasip1` instead of `unknown`? For wasmtime, we could just re-use `add_to_linker_sync` and for `js_` runtime we could `host_interface.define_func()` for the wasi interfaces to map to their `js_sys` equivalents.

Could this approach also work?

**Comment by DouglasDwyer** [comment]
Of course, you could continue to target `wasip1` instead if that supports your use case. Currently, that would involve manually binding whatever WASI functions you need using [`wasm_runtime_layer::Imports`](https://docs.rs/wasm_runtime_layer/0.4.2/wasm_runtime_layer/struct.Imports.html). Alternately, we could explore adding WASI support as an extension/optional feature of this crate - but we would need to figure out how it should behave with each backend, especially since parts of WASI (like opening sockets) are unsupported on web platforms.

**Comment by DougAnderson444** [comment]
I started looking into supporting `wasip1` and came to similar conclusions. Which appear to be more effort than I can spare right now.

It turns out, sticking to `wasm32-unknown-unknown`, with `random` specifically, I did find a [custom function](https://docs.rs/getrandom/latest/getrandom/macro.register_custom_getrandom.html) which supports your original idea to: 

> add a call to a custom WASM function that your component imports and the host supplies

I tested this out, and it works quite well! It was actually a lot easier than I thought:

```rs
use bindings::component::plugin::host::random_byte;

/// Custom function to use the import for random byte generation.
///
/// We do this is because "js" feature is incompatible with the component model
/// if you ever got the __wbindgen_placeholder__ error when trying to use the `js` feature
/// of getrandom, you have hit the same challenge.
fn imported_random(dest: &mut [u8]) -> Result<(), getrandom::Error> {
    // iterate over the length of the destination buffer and fill it with random bytes
    (0..dest.len()).for_each(|i| {
        dest[i] = random_byte();
    });

    Ok(())
}

register_custom_getrandom!(imported_random);
```

On the host side:

```rs
    host_interface
        .define_func(
            "random-byte",
            Func::new(
                &mut store,
                FuncType::new([], [ValueType::U8]),
                move |_store, _params, results| {
                    let random = rand::random::<u8>();
                    results[0] = Value::U8(random);
                    Ok(())
                },
            ),
        )
        .unwrap();
```

...which ironically gets fill isomorphically on native and web with `rand` and `getrandom`

```toml
[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2", features = ["js"] }
```

Full solution [can be found here](https://github.com/DougAnderson444/rdx/blob/27b0e16273f82b5d02accc2043887edc1526e643/examples/random/src/lib.rs#L15) others who stumble upon this issue.

I appreciate the discussion, ideas, and sounding board! I think this closes the topic of integrating `rand` usign this crate, so I'll close this issue accordingly.
